spring.application.name=AngularCURD_backend

spring.datasource.url=jdbc:mysql://localhost:3306/spring-angular
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

eureka.client.registerWithEureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance=localhost

//Swagger-config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true